<?php

/**
 * Implements hook_menu().
 */
function commerce_gd_dashboard_menu() {

  $items['admin/commerce/exports/bilan-comptable'] = array(
    'title' => 'Bilan comptable drupal',
    'access arguments' => array('view the administration theme'),
    'page callback' => 'drupal_get_form',
    'page arguments' => array('commerce_gd_dashboard_export_bilan_comptable'),
    'file' => 'commerce_gd_dashboard.export.inc',
    'type' => MENU_CALLBACK,
  );

  return $items;
}
